# Generated by Django 3.2.3 on 2021-05-31 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoryModal',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='userModal',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lasetName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('profile', models.ImageField(upload_to='upload')),
            ],
        ),
        migrations.CreateModel(
            name='postModal',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('ptitle', models.CharField(max_length=140)),
                ('pdate', models.DateTimeField(auto_now_add=True)),
                ('pdesc', models.TextField(max_length=2000)),
                ('pthumbnail', models.ImageField(upload_to='upload')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.categorymodal')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.usermodal')),
            ],
        ),
    ]
