# Generated by Django 3.2.3 on 2021-05-31 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodal',
            name='desc',
            field=models.TextField(default='', max_length=2000, null=True),
        ),
    ]
